[package]
name = "its"
version = "0.0.2"
edition = "2024"
authors = ["Oignontom8283"]
description = "Interactive Terminal's Selector - A fast, CLI-oriented user selection tool. (Work In Progress)"
license = "AGPL-3.0"
repository = "https://github.com/Oignontom8283/its"

[dependencies]
clap = { version = "4.6.4", features = ["derive"] }
crossterm = "0.29.0"
nucleo = "0.5.0"
ratatui = "0.30.2"
